name: Windows binary build

on:
  workflow_dispatch:

jobs:
  win64_build:
    name: Build x64 binaries
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: choco install upx
      - name: Build binaries
        run: |
          cmake . -S. -B _build -A x64 -G "Visual Studio 16 2019"
          cmake --build _build --config Release
      - name: Compress binaries
        run: |
          echo "Size:"
          echo ((Get-Item _build/Release/ccon.exe).length)
          upx -9 _build/Release/ccon.exe
          echo "Size after upx:"
          echo ((Get-Item _build/Release/ccon.exe).length)
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: ccon-win-x64.exe
          path: _build/Release/ccon.exe

  win32_build:
    name: Build x86 binaries
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: choco install upx
      - name: Build binaries
        run: |
          cmake . -S. -B _build -A Win32 -G "Visual Studio 16 2019"
          cmake --build _build --config Release
      - name: Compress binaries
        run: |
          echo "Size:"
          echo ((Get-Item _build/Release/ccon.exe).length)
          upx -9 _build/Release/ccon.exe
          echo "Size after upx:"
          echo ((Get-Item _build/Release/ccon.exe).length)
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: ccon-win-x86.exe
          path: _build/Release/ccon.exe
